version: 0.2

env:
    variables:
        S3_BUCKET: "javabipe/examsecure-ui/"
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install --ignore-engines
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $S3_BUCKET
artifacts:
  files:
    - '**/*'
