name: Build and Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Build & Test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - name: "Build packages"
        run: yarn build
        env:
          CI: ""
      - name: "Run tests and generate coverage report"
        run: yarn test -- -- -- --coverage
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.3.1
